version: '2'

services:
  ewbf:
    container_name: ewbf
    build: .
    environment:
      STARTUP_DELAY: "${STARTUP_DELAY}"
      SERVER: "${SERVER}"
      ADDRESS: "${ADDRESS}"
      WORKER: "${WORKER}"
      PASS: "${PASS}"
      PORT: "${PORT}"
    ports:
      - "42000:42000"
    volumes:
      - "/var/log/ewbf.log:/var/log/ewbf.log"
